---
platform: linux

image_resource:
    type: docker-image
    source:
      repository: your-repo/bosh-utils
      tag: 'latest'

params:
  release_name:
  github_owner:
  github_repository:

inputs:
- name: target-version
- name: release
outputs:
- name: release-notes

run:
  path: bash
  args:
  - -ec
  - |
    release_version=$(cat target-version/version)

    release_tarball_name="${github_repository}-${release_version}.tgz"
    release_sha=$(sha1sum release/*.tgz | awk '{print $1}')
    cat <<EOF > "release-notes/note.md"
    ## BOSH Manifest
    \`\`\` yaml
    # for using in BOSH Deployment manifest
    ---
    releases:
    - name: ${release_name}
      version: ${release_version}
      url: https://github.com/${github_owner}/${github_repository}/releases/download/${release_version}/${release_tarball_name}
      sha1: ${release_sha}
    \`\`\`
    EOF
