---
platform: linux

image_resource:
    type: docker-image
    source:
      repository: paymentshubrebels/bosh-utils
      tag: 'latest'

params:
  release_name:
  github_owner:  

inputs:
- name: version  
- name: release
outputs:
- name: release-notes

run:
  path: bash
  args:
  - -ec
  - |
    release_version=$(cat version/version)
    release_tarball_name="${release_name}-boshrelease-${release_version}.tgz"
    release_sha=$(sha1sum release/*.tgz | awk '{print $1}')
    cat <<EOF > "release-notes/note.md"
    ## BOSH Manifest
    \`\`\` yaml
    # for using in BOSH Deployment manifest
    ---
    name: $release_name
    releases:
    - name: $release_name
      version: ${release_version}
      url: https://github.com/${github_owner}/${release_name}-boshrelease/releases/download/${release_version}/${release_tarball_name}
      sha1: ${release_sha}
    \`\`\`
    EOF