---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paymentshubrebels/bosh-utils
    tag: 'latest'

params:
  release:
  version:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:

run:
  path: /bin/bash
  args:
    - -ec
    - |
    
      bosh --non-interactive delete-release "${release}/${version} --force
      
