---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paymentshubrebels/bosh-utils
    tag: 'latest'

params:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:

run:
  path: /bin/bash
  args:
    - -ec
    - |
      for release in $(bosh releases | awk '{print $1}'); do
        bosh --non-interactive delete-release $release --force
      done
