- url: "https://github.com/python/cpython/archive/v2.7.6.tar.gz"
  bosh_blob_path: Python-2.7.6.tgz
- url: "https://github.com/pypa/pip/archive/1.5.2.tar.gz"
  bosh_blob_path: pip-1.5.2.tar.gz
- url: "https://github.com/pypa/setuptools/archive/2.2.tar.gz"
  bosh_blob_path: setuptools-2.2.tar.gz
- url: "https://github.com/python/cpython/archive/v3.8.1.tar.gz"
  bosh_blob_path: Python-3.8.1.tgz
- url: "https://github.com/libffi/libffi/releases/download/v3.3/libffi-3.3.tar.gz"
  bosh_blob_path: libffi-3.3.tar.gz