---
- url: "https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-kuromoji/analysis-kuromoji-7.6.2.zip"
  bosh_blob_path: analysis-kuromoji/analysis-kuromoji-7.6.2.zip
- url: "https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-7.6.2.zip"
  bosh_blob_path: repository-s3/repository-s3-7.6.2.zip
- url: "https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-gcs/repository-gcs-7.6.2.zip"
  bosh_blob_path: repository-gcs/repository-gcs-7.6.2.zip 
- url: "https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-azure/repository-azure-7.6.2.zip"
  bosh_blob_path: repository-azure/repository-azure-7.6.2.zip
- url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-no-jdk-linux-x86_64.tar.gz"
  bosh_blob_path: elasticsearch/elasticsearch-7.6.2.tar.gz
