---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paymentshubrebels/bosh-utils
    tag: 'latest'

params:
  deployment:   
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:

run:
  path: /bin/bash
  args:
    - -ec
    - |
       for errand in $(bosh -d "$deployment" errands); do
          bosh -d "$deployment" run-errand "$errand"
       done
