---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paymentshubrebels/bosh-utils
    tag: 'latest'

inputs:
- name: app-source-code
- name: bosh-toolkit

run:
  path: bash
  args:
  - -exc
  - |
    workdir=$(pwd)
    pushd "${workdir}/app-source-code"
      currentCommitid=$(git rev-parse HEAD)
      echo "current tag - ${currentCommitid}"
      git fetch --tags
      if git show-ref --tags | egrep -q "^${currentCommitid}"
      then
          echo "Found tag"
          exit 1
      else
          echo "Tag not found"
      fi
    popd

        