---
name: cmak

releases:
- name: cmak
  version: ((target_version))

- name: bpm
  version: 1.1.0
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.0
  sha1: 82e83a5e8ebd6e07f6ca0765e94eb69e03324a19

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 456.latest

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: cmak
  azs: [z1, z2, z3]
  instances: 1
  vm_resources:
    cpu: 1
    ram: 1024
    ephemeral_disk_size: 10240
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: cmak
    release: cmak
    consumes:
      kafka: { deployment: kafka, optional: true}
      zookeeper: { deployment: kafka, optional: true}
    properties:
      username: admin
      password: ((cmak-password))

variables:
- name: cmak-password
  type: password

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false
