---
name: elasticsearch

releases:
- name: elasticsearch
  version: ((target_version))

stemcells:
- os: ubuntu-xenial
  alias: xenial
  version: latest

instance_groups:
- name: elasticsearch-master
  jobs:
  - name: elasticsearch
    release: elasticsearch
    properties:
      elasticsearch:
        node:
          allow_master: true
          allow_data: true
  instances: 1
  stemcell: xenial
  update:
    max_in_flight: 1
    serial: true
  azs:
  - z1
  vm_type: medium
  persistent_disk: 1024
  networks:
  - name: concourse
- name: pre-upgrade
  lifecycle: errand
  jobs:
  - name: pre-upgrade
    release: elasticsearch
  instances: 1
  stemcell: xenial
  azs:
  - z1
  vm_type: medium
  networks:
  - name: concourse
- name: post-upgrade
  lifecycle: errand
  jobs:
  - name: post-upgrade
    release: elasticsearch
  instances: 1
  stemcell: xenial
  azs:
  - z1
  vm_type: medium
  networks:
  - name: concourse

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
