name: filebeat

releases:
  - name: filebeat
    version: ((target_version))
 
stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

instance_groups:
  - name: filebeat
    instances: 1
    azs:       [z1]
    stemcell:  default
    vm_type: medium
    networks:
      - name: concourse
    jobs:
      - name: filebeat
        release: filebeat
        properties:
          filebeat:
            configuration: |
              filebeat.inputs:
              - type: log
                paths:
                  - /var/vcap/sys/log/*/*.log
              output.file:
                path: "/tmp"
                filename: filebeat
                rotate_every_kb: 10000
update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000  
