---
name: kafka

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: kafka
  azs: [z1, z2, z3]
  instances: 1
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 10240
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  - name: kafka
    release: kafka
    properties:
      offsets:
        topic:
          replication:
            factor: 1
      transaction:
        state:
          log:
            replication:
              factor: 1
            min:
              isr: 1
  - name: kafka-manager
    release: kafka
    properties:
      username: admin
      password: ((kafka-manager-password))
- name: sanity-test
  azs: [z1, z2, z3]
  instances: 1
  lifecycle: errand
  vm_resources:
    cpu: 1
    ram: 1024
    ephemeral_disk_size: 10240
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sanitytest
    release: kafka
    consumes:
      zookeeper:
        deployment: zookeeper

variables:
- name: kafka-manager-password
  type: password

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: true

stemcells:
- alias:   default
  os:      ubuntu-xenial
  version: latest
  
releases:
- name:    kafka
  version: latest
- name: bpm
  version: 1.1.0
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.0
  sha1: 82e83a5e8ebd6e07f6ca0765e94eb69e03324a19
- name: zookeeper
  version: 0.0.10
  sha1: 37abc951e6a3cacb4607186a42d33101ebd96500
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/zookeeper/zookeeper-0.0.10-ubuntu-xenial-456.3-20190807-230924-288267589-20190807230933.tgz