---
name: kafka

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: kafka
  azs: [z1, z2, z3]
  instances: 2
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 10240
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: kafka
    release: kafka
    properties:
      delete_topic: true
      offsets:
        topic:
          replication:
            factor: 2
      transaction:
        state:
          log:
            replication:
              factor: 1
            min:
              isr: 1
  - name: cmak
    release: cmak
    properties:
      username: admin
      password: ((cmak-password))
- name: zookeeper
  azs: [z1, z2, z3]
  instances: 1
  vm_resources:
    cpu: 1
    ram: 1024
    ephemeral_disk_size: 10240
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}

- name: sanity-test
  azs: [z1, z2, z3]
  instances: 1
  lifecycle: errand
  vm_resources:
    cpu: 1
    ram: 1024
    ephemeral_disk_size: 10240
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sanitytest
    release: kafka

variables:
- name: cmak-password
  type: password

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: true

stemcells:
- alias:   default
  os:      ubuntu-xenial
  version: latest
  
releases:
- name:    kafka
  version: latest
- name: bpm
  version: 1.1.0
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.0
  sha1: 82e83a5e8ebd6e07f6ca0765e94eb69e03324a19

- name: zookeeper
  version: 0.2.0
  url: https://github.com/PaymentsHubRebels/zookeeper-release/releases/download/0.2.0/zookeeper-boshrelease-0.2.0.tgz
  sha1: 2faeeeffdc4acaa38bae121511d00b36e771eb11

- name: cmak
  version: 0.2.0
  url: https://github.com/PaymentsHubRebels/cmak-boshrelease/releases/download/0.2.0/cmak-boshrelease-0.2.0.tgz
  sha1: 8ce61ebcd86817cefc79ba5a7e10e112f013633e