
---
name: kibana
releases:
- name: kibana
  version: ((target_version))

- name: elasticsearch
  version: 0.31.0
  url: https://github.com/bosh-rebels/elasticsearch-boshrelease/releases/download/0.31.0/elasticsearch-boshrelease-0.31.0.tgz
  sha1: c01ba3338904f6e5fa48dc3358ac20c0d005506f


stemcells:
- os: ubuntu-xenial
  alias: xenial
  version: latest

instance_groups:
- name: kibana-and-elastic
  jobs:
  - name: elasticsearch
    release: elasticsearch
    properties:
      elasticsearch:
        node:
          allow_master: true
          allow_ingest: true
          allow_data: true
  - name: kibana
    release: kibana
  instances: 1
  stemcell: xenial
  update:
    max_in_flight: 1
    serial: true
  azs:
  - z1
  - z2
  - z3
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 10240
  persistent_disk: 1024
  networks:
  - name: default

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
