
---
name: kibana
releases:
- name: elasticsearch
  version: 0.30.0
  url: https://github.com/bosh-rebels/elasticsearch-boshrelease/releases/download/0.30.0/elasticsearch-boshrelease-0.30.0.tgz
  sha1: 89852eaa5bb309b4809866a422d1fef9449a7c80
- name: kibana
  version: latest

stemcells:
- os: ubuntu-xenial
  alias: xenial
  version: latest

instance_groups:
- name: elasticsearch-master
  jobs:
  - name: elasticsearch
    release: elasticsearch
    properties:
      elasticsearch:
        node:
          allow_master: true
          allow_data: true
  - name: kibana
    release: kibana
  instances: 1
  stemcell: xenial
  update:
    max_in_flight: 1
    serial: true
  azs:
  - z1
  - z2
  - z3
  vm_resources:
    cpu: 1
    ram: 1024
    ephemeral_disk_size: 10240
  persistent_disk: 1024
  networks:
  - name: default

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
