name: metricbeat

releases:
- name: metricbeat
  version: ((target_version))

- name: elasticsearch
  version: 0.31.0
  url: https://github.com/bosh-rebels/elasticsearch-boshrelease/releases/download/0.31.0/elasticsearch-boshrelease-0.31.0.tgz
  sha1: 9217d2e1091b3d53dc48f89f8732b5745f087506  

stemcells:
- alias:   default
  os:      ubuntu-xenial
  version: latest

instance_groups:
- name: metricbeat
  instances: 1
  azs:       [z1]
  stemcell:  default
  vm_type: default
  networks:
    - name: default
  jobs:
  - name: metricbeat
    release: metricbeat
- name: elasticsearch
  instances: 1
  azs:       [z1]
  stemcell:  default
  vm_type: default
  networks:
    - name: default
  jobs:
  - name: elasticsearch
    release: elasticsearch
    properties:
      elasticsearch:
        node:
          allow_master: true
          allow_data: true 

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000  

