---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: your-repo/bosh-utils
    tag: 'latest'

params: {}

inputs:
- name: app-source-code

run:
  path: bash
  args:
  - -ec
  - |
    pushd app-source-code
      if [[ -d spec ]]; then
        bundle install
        bundle exec rspec spec/**/*.rb
      else
        echo "spec folder not found. Skipping..."
      fi
    popd