- url: "https://github.com/Yelp/kafka-utils/archive/v3.2.0.tar.gz"
  bosh_blob_path: v3.2.0.tar.gz
- url: "192.168.1.13:9000/blobs/kafka-manager-1.3.3.4.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20200412%2F%2Fs3%2Faws4_request&X-Amz-Date=20200412T091922Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=1b063d06037ba0fa8689381cee55de023741af9ca759ba5fd895d6a4410f10c7"
  bosh_blob_path: kafka/kafka-manager-1.3.3.4.zip
- url: "https://downloads.apache.org/kafka/2.4.0/kafka_2.12-2.4.0.tgz"
  bosh_blob_path: kafka/kafka_2.12-2.4.0.tgz
- url: "https://s3.amazonaws.com/bosh-packages-java-release/8f7f0dda-a4af-4aa5-7a36-234c3cb25065"
  bosh_blob_path: java/jdk8u192-b03.tar.gz