bosh_release_repo_name: kafka-boshrelease
bosh_release_branch: master
stemcell_version_family: latest
release_name: kafka
github_repository: kafka-boshrelease
github_owner: bosh-rebels
app_initial_version : 2.6.0