---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: diefida/bosh-utils
    tag: 'latest'

params:
  release_name:
  final: false

inputs:
- name: source-code
- name: blobs
- name: version

outputs:
- name: release

run:
  path: bash
  args:
  - -ec
  - |
    bosh_options=(--force)

    if [[ "$final" == "true" ]]; then
      bosh_options=("${bosh_options[@]}" --final --version=$(cat version/version))
    fi

    pushd blobs
      for blob in $(find * -type f); do
        bosh add-blob --dir=../source-code "$blob" "$blob"
      done
    popd

    pushd source-code
      bosh create-release "${bosh_options[@]}" --tarball=../release/${release_name}-boshrelease-$(cat version/version).tgz
    popd