resources:
- name: bosh-toolkit
  type: git
  source:
    uri: https://github.com/((github_owner))/bosh-toolkit
    branch: master
    paths:
      - pipelines/*.yml

jobs:
- name: set-all-pipelines
  plan:
  - get: bosh-toolkit
    trigger: true
  - set_pipeline: bosh-utils-image
    file: bosh-toolkit/pipelines/docker.yml
  - set_pipeline: metricbeat
    file: bosh-toolkit/pipelines/bosh_release.yml
    vars:
      release_name: metricbeat
      stemcell_version_family: latest
  - set_pipeline: elasticapm
    file: bosh-toolkit/pipelines/bosh_release.yml
    vars:
      release_name: elasticapm
      stemcell_version_family: latest
  - set_pipeline: kafka
    file: bosh-toolkit/pipelines/bosh_release.yml
    vars:
      release_name: kafka
      stemcell_version_family: "456.40"
  - set_pipeline: redis
    file: bosh-toolkit/pipelines/bosh_release.yml
    vars:
      release_name: redis
      stemcell_version_family: latest