resources:
- name: bosh-toolkit
  type: git
  source:
    uri: https://github.com/((github_owner))/bosh-toolkit
    branch: master
    paths:
      - pipelines/*.yml

jobs:
- name: set-all-pipelines
  plan:
  - get: bosh-toolkit
    trigger: true
  - set_pipeline: bosh-utils-image
    file: bosh-toolkit/pipelines/docker.yml

  - set_pipeline: zookeeper
    file: bosh-toolkit/pipelines/bosh_release.yml
    var_files:
    - bosh-toolkit/config/zookeeper/pipeline_vars.yml

  - set_pipeline: kafka
    file: bosh-toolkit/pipelines/bosh_release.yml
    var_files:
    - bosh-toolkit/config/kafka/pipeline_vars.yml

  - set_pipeline: cmak
    file: bosh-toolkit/pipelines/bosh_release.yml
    var_files:
    - bosh-toolkit/config/cmak/pipeline_vars.yml

  - set_pipeline: redis
    file: bosh-toolkit/pipelines/bosh_release.yml
    var_files:
    - bosh-toolkit/config/redis/pipeline_vars.yml
  
  - set_pipeline: elasticsearch
    file: bosh-toolkit/pipelines/bosh_release.yml
    var_files:
    - bosh-toolkit/config/elasticsearch/pipeline_vars.yml
  
  - set_pipeline: elasticapm
    file: bosh-toolkit/pipelines/bosh_release.yml
    var_files:
    - bosh-toolkit/config/elasticapm/pipeline_vars.yml

  - set_pipeline: metricbeat
    file: bosh-toolkit/pipelines/bosh_release.yml
    var_files:
    - bosh-toolkit/config/metricbeat/pipeline_vars.yml