azs:
- cloud_properties:
    availability_zone: eu-west-2a
  cpi: dfa23e7939c2c2bfbdf3
  name: z1
- cloud_properties:
    availability_zone: eu-west-2b
  cpi: dfa23e7939c2c2bfbdf3
  name: z2
- cloud_properties:
    availability_zone: eu-west-2c
  cpi: dfa23e7939c2c2bfbdf3
  name: z3
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: default
  workers: 5
disk_types:
- cloud_properties:
    type: gp2
  disk_size: 10000
  name: 10GB
- cloud_properties:
    type: gp2
  disk_size: 20000
  name: 20GB
- cloud_properties:
    iops: 500
    type: io1
  disk_size: 100000
  name: 100GB
- cloud_properties:
    iops: 500
    type: io1
  disk_size: 200000
  name: 200GB
- disk_size: 30000
  name: default
networks:
- name: default
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0012134ee339e234c
    dns:
    - 192.168.240.2
    gateway: 192.168.240.1
    range: 192.168.240.0/26
    reserved:
    - 192.168.240.1-192.168.240.5
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-0b6b8f73b769037f8
    dns:
    - 192.168.240.66
    gateway: 192.168.240.65
    range: 192.168.240.64/26
    reserved:
    - 192.168.240.65-192.168.240.70
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0f4fb16e958507773
    dns:
    - 192.168.240.130
    gateway: 192.168.240.129
    range: 192.168.240.128/26
    reserved:
    - 192.168.240.129-192.168.240.134
  type: manual
- name: vip
  type: vip
vm_types:
- cloud_properties:
    ephemeral_disk:
      size: 25000
    instance_type: t3.medium
  name: default
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: t3.small
  name: small
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.large
  name: medium
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: r5.large
  name: large
