azs:
- name: z1
  cloud_properties:
    availability_zone: eu-west-2a
  cpi: dfa23e7939c2c2bfbdf3
- name: z2
  cloud_properties:
    availability_zone: eu-west-2b
  cpi: dfa23e7939c2c2bfbdf3
- name: z3
  cloud_properties:
    availability_zone: eu-west-2c
  cpi: dfa23e7939c2c2bfbdf3

vm_types:
- name: small
  cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: t3.small

- name: medium
  cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: m4.large

- name: large
  cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: r5.large
    
disk_types:
- cloud_properties:
    type: gp2
  disk_size: 10000
  name: 10GB
- cloud_properties:
    type: gp2
  disk_size: 20000
  name: 20GB
- cloud_properties:
    iops: 500
    type: io1
  disk_size: 100000
  name: 100GB
- cloud_properties:
    iops: 500
    type: io1
  disk_size: 200000
  name: 200GB

networks:
- name: default
  type: manual
  subnets:
  - range: 192.168.240.0/26
    gateway: 192.168.240.1
    azs: [z1]
    dns: [192.168.240.2]
    reserved: [192.168.240.1-192.168.240.5]
    cloud_properties:
      subnet: subnet-0012134ee339e234c
  - range: 192.168.240.64/26
    gateway: 192.168.240.65
    azs: [z2]
    dns: [192.168.240.66]
    reserved: [192.168.240.65-192.168.240.70]
    cloud_properties:
      subnet: subnet-0bec2b5964d1c3082
  - range: 192.168.240.128/26
    gateway: 192.168.240.129
    azs: [z3]
    dns: [192.168.240.130]
    reserved: [192.168.240.129-192.168.240.134]
    cloud_properties:
      subnet: subnet-0b62cce6069802616
- name: vip
  type: vip
    
compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
