---
platform: linux

image_resource:
  type: docker-image
  source:
  repository: diefida/bosh-utils
  tag: 'latest'

params:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:

run:
  path: /bin/bash
  args:
    - -ec
    - |
      for stemcell in $(bosh stemcells | awk '{print $1"/"$2}'); do
        bosh --non-interactive delete-stemcell $stemcell --force
      done
  
  