---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: diefida/bosh-utils
    tag: 'latest'

params:
  AWS_REGION:
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:

inputs:
  - name: binary-release

run:
  path: /bin/bash
  args:
    - -exc
    - |
      export AWS_DEFAULT_REGION="${AWS_REGION}"
      export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY}"
      export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_KEY}"
      apt-get update & apt-get install -y python3-pip & pip3 install awscli
      export PATH=$PATH:/usr/local/bin
      pushd binary-release
      release=$(ls | awk -F"-" '{print $1}')
      for rel in $release; do
        aws s3 cp ${rel}* s3://binary-releases-repo-rebels/$rel/
      done
      popd

