---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: diefida/bosh-utils
    tag: 'latest'

params:
  release_name:
  deployment:
  os: ubuntu-xenial    
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:

inputs:
  - name: target-version
  - name: running-version
  - name: ubuntu-xenial
outputs:
  - name: binary-release

run:
  path: /bin/bash
  args:
    - -ec
    - |
      running-version=$(cat running-version/version)
      target-version=$(cat target-version/version)
      if [[ "$target-version" != "$running-version" ]]; then
        echo "Terget version $target-version is not equal to $running-version , so exporting bosh release."
        stemcell_version=$(cat ubuntu-xenial/version)
        bosh -d "$deployment" \
            export-release "${release_name}/$(cat target-version/version)" "${os}/${stemcell_version}" \
            --dir=binary-release/
      else
        echo "Terget version $target-version is equal to $running-version , so NOT exporting bosh release."
      fi