---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: diefida/bosh-utils
    tag: 'latest'

params:
  release_name:
  deployment:
  os: ubuntu-xenial    
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:

inputs:
  - name: target-version
  - name: ubuntu-xenial
  - name: bosh-toolkit
outputs:
  - name: binary-release
  - name: offline-release

run:
  path: /bin/bash
  args:
    - -exc
    - |
      export target_version=$(cat target-version/version)
      export stemcell_version=$(cat ubuntu-xenial/version)
      export release_name="${release_name}"
      export offline_tarball="${release_name}-offline-release-${target_version}.tgz"

      pushd bosh-toolkit/manifests
      release_list=$(ruby ../tasks/export-release/release_version.rb)

      for release in $release_list; do
        bosh -d "$deployment" \
          export-release "${release}" "${os}/${stemcell_version}" \
          --dir=../../binary-release/
      done  
      popd

      pushd offline-release
        mkdir -p releases stemcell 
        cp ../ubuntu-xenial/*.tgz stemcell/
        cp ../binary-release/*.tgz releases/
        tar -cvf ${offline_tarball} *
        rm -rf releases stemcell 
      popd
