---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paymentshubrebels/bosh-utils
    tag: 'latest'

params:
  release_name:
  deployment:
  os: ubuntu-xenial    
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:

inputs:
  - name: ubuntu-xenial
  - name: target-version
outputs:
  - name: compiled-release

run:
  path: /bin/bash
  args:
    - -ec
    - |
      stemcell_version=$(cat ubuntu-xenial/version)
      bosh -d "$deployment" \
           export-release "${release_name}/$(cat target-version/version)" "${os}/${stemcell_version}" \
           --dir=compiled-release/