---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: diefida/bosh-utils
    tag: 'latest'

params:
  release_name:
  deployment:
  os: ubuntu-xenial    
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:

inputs:
  - name: target-version
  - name: ubuntu-xenial
  - name: bosh-toolkit
outputs:
  - name: binary-release

run:
  path: /bin/bash
  args:
    - -ec
    - |
      export target_version=$(cat target-version/version)
      export stemcell_version=$(cat ubuntu-xenial/version)
      export release_name="${release_name}"

      pushd bosh-toolkit/manifests
      release_list=$(ruby <<-RUBYFILE
        require "yaml"
          YAML.load_file(ENV["release_name"]+".yml")["releases"].each do |rel| 
            if "#{rel["name"]}" == ENV["release_name"]
              rel["version"]=ENV["target_version"] 
            end
          puts "#{rel["name"]}/#{rel["version"]}"
          end
      RUBYFILE
      )

      for release in $release_list; do
        bosh -d "$deployment" \
          export-release "${release}" "${os}/${stemcell_version}" \
          --dir=binary-release/
      done
      popd